---
- name: "Ensure Mopidy configuration directory exists"
  file:
    path: /etc/mopidy
    state: directory
    owner: "{{ mopidy_user }}"
    mode: 0755
- name: "Configure Mopidy"
  template:
    src: templates/mopidy.conf.j2
    dest: /etc/mopidy/mopidy.conf
    owner: "{{ mopidy_user }}"
