---
- name: "Ensure Mopidy configuration directory exists"
  become: true
  file:
    path: /etc/mopidy
    state: directory
    owner: root
    group: root
    mode: 0755
- name: "Configure Mopidy"
  become: true
  template:
    src: templates/mopidy.conf.j2
    dest: /etc/mopidy/mopidy.conf
    owner: root
    group: root
    mode: 0644
