---
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure dependencies for installation are installed"
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gnupg
      - python3-debian
      - python3-pip
- name: "Ensure Mopidy APT repo is present"
  become: true
  ansible.builtin.deb822_repository:
    name: mopdiy
    types: [deb]
    uris: "https://apt.mopidy.com/"
    signed_by: "https://apt.mopidy.com/mopidy.gpg"
    suites: [bullseye]
    components: [main contrib non-free]
    architectures: armhf
- name: "Ensure Mopidy is installed"
  become: true
  apt:
    name: "mopidy={{ mopidy_version }}"
    state: present
  notify:
    - restart mopidy
- name: "Ensure Scrobbler plugin for Mopidy is installed"
  become: true
  apt:
    name: "mopidy-scrobbler={{ mopidy_scrobbler_version }}"
    state: "{{ 'present' if mopidy_lastfm_enabled else 'absent' }}"
  notify:
    - restart mopidy
- name: "Ensure Spotify plugin for Mopidy is installed"
  become: true
  apt:
    name: "mopidy-spotify={{ mopidy_spotify_version }}"
    state: "{{ 'present' if mopidy_spotify_enabled else 'absent' }}"
  notify:
    - restart mopidy
- name: "Ensure pip3 is installed"
  become: true
  apt:
    name: python3-pip
    state: present
- name: "Ensure Iris plugin for Mopidy is installed"
  become: true
  pip:
    executable: pip3
    name: Mopidy-Iris
    version: "{{ mopidy_iris_version }}"
    state: present
  notify:
    - restart mopidy

# Old plugins:
# Mopidy-Spotify-Tunigo
# Mopidy-Spotify-Web
