---
# tasks file for mopidy

- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure GnuPG is installed"
  become: true
  apt:
    name: gnupg
    state: present
- name: "Ensure Mopidy APT key is present"
  become: true
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present
    validate_certs: False  # TEMP
- name: "Ensure Mopidy APT repo is present"
  become: true
  apt_repository:
    repo: deb http://apt.mopidy.com/ jessie main contrib non-free
    state: present
    filename: mopidy
    update_cache: yes
    validate_certs: no
- name: "Ensure Mopidy is installed"
  become: true
  apt:
    name: mopidy=2.1.0-1
    state: present
  notify:
    - restart mopidy
- name: "Ensure Scrobbler plugin for Mopidy is installed"
  become: true
  apt:
    name: mopidy-scrobbler=1.1.1-3
    state: present
  notify:
    - restart mopidy
- name: "Ensure Spotify plugins for Mopidy are installed (apt)"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mopidy-spotify=3.0.0-0mopidy1
    - mopidy-spotify-tunigo=1.0.0-0mopidy1
  notify:
    - restart mopidy
- name: "Ensure Soundcloud plugin for Mopidy is installed"
  become: true
  apt:
    name: mopidy-soundcloud=2.0.2-2
    state: present
  notify:
    - restart mopidy
- name: "Ensure pip is installed"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
- name: "Ensure Spotify plugins for Mopidy are installed (pip)"
  become: true
  pip:
    name: Mopidy-Spotify-Web
    version: 0.3.0
    state: present
  notify:
    - restart mopidy
- name: "Ensure Iris plugin for Mopidy is installed"
  become: true
  pip:
    name: Mopidy-Iris
    version: 2.14.3
    state: present
  notify:
    - restart mopidy
