---
- name: "Ensure /etc/sources.list.d exists"
  become: true
  file:
    path: /etc/sources.list.d
    state: directory
    mode: 0755
- name: "Ensure GnuPG is installed"
  become: true
  apt:
    name: gnupg
    state: present
- name: "Ensure /usr/local/share/keyrings exists"
  become: true
  file:
    path: /usr/local/share/keyrings
    state: directory
    mode: 0755
- name: "Ensure Mopidy APT key is present"
  become: true
  get_url:
    url: https://apt.mopidy.com/mopidy.gpg
    dest: /usr/local/share/keyrings/mopidy-archive-keyring.gpg
    mode: 0644
- name: "Ensure Mopidy APT repo is present"
  become: true
  apt_repository:
    repo: deb [signed-by=/usr/local/share/keyrings/mopidy-archive-keyring.gpg] https://apt.mopidy.com/ buster main contrib non-free
    state: present
    filename: mopidy
    update_cache: yes
- name: "Ensure Mopidy is installed"
  become: true
  apt:
    name: "mopidy={{ mopidy_version }}"
    state: present
  notify:
    - restart mopidy
- name: "Ensure Scrobbler plugin for Mopidy is installed"
  become: true
  apt:
    name: "mopidy-scrobbler={{ mopidy_scrobbler_version }}"
    state: "{{ 'present' if mopidy_lastfm_enabled else 'absent' }}"
  notify:
    - restart mopidy
- name: "Ensure Spotify plugin for Mopidy is installed"
  become: true
  apt:
    name: "mopidy-spotify={{ mopidy_spotify_version }}"
    state: "{{ 'present' if mopidy_spotify_enabled else 'absent' }}"
  notify:
    - restart mopidy
- name: "Ensure pip3 is installed"
  become: true
  apt:
    name: python3-pip
    state: present
- name: "Ensure Iris plugin for Mopidy is installed"
  become: true
  pip:
    executable: pip3
    name: Mopidy-Iris
    version: "{{ mopidy_iris_version }}"
    state: present
  notify:
    - restart mopidy

# Old plugins:
# Mopidy-Spotify-Tunigo
# Mopidy-Spotify-Web
